apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-
namespace: aks-store-demo-prod

replicas:
  - name: store-front
    count: 3
  - name: store-admin
    count: 3
  - name: order-service
    count: 3
  - name: product-service
    count: 3
  - name: makeline-service
    count: 2

patchesStrategicMerge:
  - resources-patch.yaml
  - hpa-patch.yaml

commonLabels:
  environment: production
  version: v1.0.0
