apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: aks-store-demo
type: Opaque
data:
  azurestorageaccountname: YWtzc3RvcmVkZW1vMTcyMTMzMzE2OA==  # Replace with base64 encoded storage account name
  azurestorageaccountkey: <REPLACE_WITH_BASE64_ENCODED_KEY>    # Replace with base64 encoded storage key
