apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        "kubernetes.io/os": linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: product-service
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          image: ghcr.io/azure-samples/aks-store-demo/product-service:v1.0.0
          ports:
            - containerPort: 3002
          env:
            - name: AI_SERVICE_URL
              value: ""
            - name: STORAGE_PATH
              value: "/mnt/azure-blob"
          volumeMounts:
            - name: azure-blob-volume
              mountPath: /mnt/azure-blob
              readOnly: false
          resources:
            requests:
              cpu: 1m
              memory: 1Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 2m
              memory: 20Mi
              ephemeral-storage: 2Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: azure-blob-volume
          persistentVolumeClaim:
            claimName: azure-blob-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3002
      targetPort: 3002
  selector:
    app: product-service
